# Generated by Django 4.2.7 on 2023-11-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_options_alter_course_table_lesson'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson',
            table='lesson',
        ),
    ]
