# Generated by Django 4.2.7 on 2023-12-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_userlesson'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlesson',
            table='user_lesson',
        ),
    ]
