# Generated by Django 4.2.7 on 2023-12-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_userlesson_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlesson',
            table='custom_user_lesson',
        ),
    ]
