# Generated by Django 4.2.7 on 2023-11-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_lesson_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
    ]
