# Generated by Django 4.2.7 on 2023-11-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lesson_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
