# Generated by Django 4.2.7 on 2023-11-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_lesson_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lesson',
        ),
    ]
