# Generated by Django 4.2.7 on 2023-12-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_userlesson_table'),
        ('user', '0002_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='courses', to='course.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
            ],
        ),
    ]
