# Generated by Django 4.2.7 on 2023-12-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_groupcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupCourse',
        ),
    ]
